### ISSUE TITLE
Dependency on package 'go-bits' which doesn't properly handle errors

### ISSUE THREAD

**Issue by momer** [LiveRamp/iabconsent#5]
Dependency on package, [go-bits](https://github.com/rupertchen/go-bits/), which has poor error handling that will panic in error scenarios, instead of returning the error and allowing the handler to handle it appropriately.

https://github.com/rupertchen/go-bits/blob/master/bits.go#L66-L104

**Comment by rupertchen** [comment]
@momer, could you provide an example where `iabconsent` is not recovering from the panic where you expect it to? The design philosophy here is to leverage panics internally within `iabconsent` to keep the logic less cluttered while not exposing them to callers of `iabconsent`.

It was an intentional choice *not* to have `go-bits` return errors on out of range indices. I'd be happy to discuss issues regarding go-bits on its issues page.

**Comment by momer** [comment]
@rupertchen on mobile, sorry for being concise.

Panic/recover is acceptable *within* a package, when calling private functions (typically nested), and *not* in exported functions. 

“By convention, no explicit panic() should be allowed to cross a package boundary. Indicating error conditions to callers should be done by returning error value.”

https://github.com/golang/go/wiki/PanicAndRecover

**Comment by rupertchen** [comment]
I am aware of the Go libraries convention with panics, but as mentioned earlier, the use of it here is a conscious decision in the name of more readable code. Fundamentally, it is inline with the spirit of array accesses, which go-bits is lightly emulating. An API that explicitly uses panics is unconventional, but not unheard of.

1. Using panics in `iabconsent`'s implementation allows for simpler, more readable code.

   In experimenting with both approaches, what tipped my decision was what I believe to be the more readable way to implement `ReadX` and `Parse` functions. By the problem's nature, if the bits are unexpectedly truncated, there is nothing the caller can do to "fix" it or try again. They must end the parse attempt and walk away with what has been gathered so far.

   The consequence of exposing such problems through `error`s instead would be heavily duplicated error handling code in `Parse` at each read of bits.

   Compare
   ```go
   	p = &Payload{}
   	p.Version = int(r.ReadBits(4))
   	p.Category = Category(r.ReadBits(8))
   	p.IsX = r.ReadBool()
   	p.IsY = r.ReadBool()
   	p.IsZ = r.ReadBool()
   ```
   to
   ```go
   	p = &Payload{}
   	if p.Version, err = int(r.ReadBits(4)); err != nil {
   		return
   	}
   	if p.Category, err = Category(r.ReadBits(8)); err != nil {
   		return
   	}
   	if p.IsX, err = r.ReadBool(); err != nil {
   		return
   	}
   	if p.IsY, err = r.ReadBool(); err != nil {
   		return
   	}
   	if p.IsZ, err = r.ReadBool(); err != nil {
   		return
   	}
   ```

2. `bits.Bitmap` panics for the same reason out-of-bounds array accesses panic.

   `bits.Bitmap#Get` is intended to conceptually operate at a similar level of abstraction as arrays and slices. `bits.Reader` further makes enough information available to the caller to avoid reading beyond the available bounds, should they choose to check it.

3. Panics that are part of the API exist, even in the standard library.

   I'll admit this area of documentation is lacking in go-bits, but I plan to address that as I have time.

   If you have a use case for go-bits where you need an error instead of a panic, I'd like to hear about it and I will prioritize adding a method that errors. That said, what I had in mind eventually was to do something in the style of `regexp` with [MustCompile](https://golang.org/pkg/regexp/#MustCompile) and [Compile](https://golang.org/pkg/regexp/#Compile) or `github.com/gorilla/context` with [Get](http://www.gorillatoolkit.org/pkg/context#Get) and [GetOk](http://www.gorillatoolkit.org/pkg/context#GetOk).

Lastly, I feel your issue primarily pertains to the go-bits package. If you have found a case where `iabconsent#Parse` is panicking, please provide it; I want to make sure that is addressed. If you'd like to discuss go-bits's implementation further, let's continue that discussion at [its repo](https://github.com/rupertchen/go-bits).

**Comment by momer** [comment]
@rupertchen I don't doubt that the current `Parse` function looks much cleaned up compared to handling errors. The main issue I see, *with this package*, and its reliance on `go-bits` is a typical scenario in which errors are ignored until thrown, recovered/rescued, and the stack trace is lost in transit.

@rupertchen if [this](https://github.com/LiveRamp/iabconsent/blob/master/parse.go#L106) specific line caused the panic, the user of this package would have no idea, and would only know that a panic, in another package, was recovered in the `Parse` function.

That said, you can close this issue, since we've discussed your design methodology here.

**Comment by rupertchen** [comment]
Providing an interesting stack trace from `Parse` is compelling to me and I have an idea of how to accomplish that while largely keeping the readability that I am after. I'll wait to close this issue as I believe it will also address the concerns you've brought up.

Thanks for spurring this conversation and stay tuned.

**Comment by adayNU** [comment]
Can we close here @rupertchen ?

**Comment by rupertchen** [comment]
I think so.
